version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: doyouremember-postgres-dev
    environment:
      POSTGRES_DB: doyouremember
      POSTGRES_USER: doyouremember
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - doyouremember-network

  # Redis para caché y sesiones
  redis:
    image: redis:7-alpine
    container_name: doyouremember-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - doyouremember-network

  # RabbitMQ para message broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: doyouremember-rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    networks:
      - doyouremember-network

  # MinIO para almacenamiento de objetos
  minio:
    image: minio/minio:latest
    container_name: doyouremember-minio-dev
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_dev:/data
    networks:
      - doyouremember-network

volumes:
  postgres_data_dev:
  redis_data_dev:
  rabbitmq_data_dev:
  minio_data_dev:

networks:
  doyouremember-network:
    driver: bridge
